### ISSUE TITLE
get more detail

### ISSUE THREAD

**Issue by selcukakbas** [Dory-dev/Feedly-Export-Save4Later#1]
I've added two more line to get more detail of saved item. it gets engagement number and summary

title: $el.attr("data-title"),
url: $el.attr("data-alternate-link"),
**enga: $el.attr("engagement-count"),
summa: $el.find(".summary")[0].innerHTML,**
time: regex.exec($el.find("span.ago").attr("title"))[1]

**Comment by Barabazs** [comment]
Sorry for the delay. I wasn't subscribed to notifications.

Enagement doesn't seem to work at all, but summary works nicely.
Could you take another look at it and open a pull request?

**Comment by Barabazs** [comment]
Script was updated with code for summary.
