### ISSUE TITLE
sourceUrl for hacker news

### ISSUE THREAD

**Issue by nevven** [Dory-dev/Feedly-Export-Save4Later#4]
Hi, when you get the json for saved hacker news submissions i get, example:
```
  {
    "title": "Hercule Poirot turns 100: The strange case of the Belgian detective",
    "url": "https://www.economist.com/books-and-arts/2020/09/26/hercule-poirot-turns-100",
    "summary": " Comments ",
    "time": "Sun, 27 Sep 2020 06:38:04 GMT",
    "sourceTitle": "Hacker News",
    "sourceUrl": "https://news.ycombinator.com/"
  },
```

The real source (of the submission to hacker news) is in "summary": " Comments ",

How can i get the url of "summary"?

tnx

**Comment by Barabazs** [comment]
Can you give me the link that is saved in Feedly?

I tried it with this link https://news.ycombinator.com/item?id=24604683 and got this:
 ```
  {
    "title": "Hercule Poirot turns 100: The strange case of the Belgian detective | Hacker News",
    "url": "https://news.ycombinator.com/item?id=24604683",
    "summary": " ",
    "time": "Tue, 06 Oct 2020 11:13:13 GMT",
    "sourceTitle": "Y Combinator",
    "sourceUrl": ""
  }
```

**Comment by nevven** [comment]
tnx for reply @Barabazs 
When you subscribe to hn rss, you don't get link you posted in head url
I think the problem is that, on hn when you click on the posted article, it directs you to the article itself (economist in this case)
https://news.ycombinator.com/news
Only if you click on `comments`, you are directed to discussions, so feedly & your script is getting the head links properly
I only wish i can get the url of the discussion in: `"summary": " Comments ",` part of the JSON if possible?

**Comment by Barabazs** [comment]
I looked into it and it's just not possible with that feed. 
But you can subscribe to https://hnrss.org/newest?link=comments
It's an open source community project that lets you customise the subscription. More info [here](https://edavis.github.io/hnrss/).

**Comment by nevven** [comment]
Thank you for the info&help, and the tool, it's very useful
