### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by mattgortner** [Dory-dev/Feedly-Export-Save4Later#7]
Hi - I came back to use the script 1 year later and something is broken...I  tried some minor debugging, but it's way outside my ability.

Here's the error: 

VM346:8 Uncaught TypeError: Cannot read properties of null (reading 'innerHTML')
    at <anonymous>:8:52
    at Array.forEach (<anonymous>)
    at convertEntries (<anonymous>:5:10)
    at <anonymous>:31:12

**Comment by Barabazs** [comment]
Hi @mattgortner thank you for flagging this.
I've updated the script with the new selectors Feedly uses. 
Can you give it a try please?

**Comment by mattgortner** [comment]
That's perfect, thanks so much!
